12 individual course pages
THM-ATLAS/vue-frontend pull request #92
Opened 2022-05-14 11:43 UTC by danielp0505

2022-05-14 16:50 UTC, hwgn requested changes

2022-05-14 16:50 UTC, hwgn commented on src/components/CourseMainPage.vue
> +    <MainpageCardModal class="exercisePanel"
Clicking on the task cards opens ID `http://localhost:8080/bkp/e/undefined/`. Since we now use API calls, you could instead get the first 5 tasks (IDs 1, 2, ..., 5) and display the information you get back.

2022-05-14 16:50 UTC, hwgn commented on src/components/CourseMainPage.vue
> +  <v-container style="background-color:rgb(var(--v-theme-primary));">
White on green is not AA compliant, so it might be better to use a different shade of surface color here instead (and then use the default text color)
![image](https://user-images.githubusercontent.com/19843204/168440966-d60307c8-a2a8-4ca2-8da7-1d600e4b1544.png)

2022-05-14 16:50 UTC, hwgn commented on src/views/CourseMainPageView.vue
> +<script setup>
Please move scripts to a new or different component, views should only be used for layouting

2022-05-14 16:50 UTC, hwgn commented on src/components/CourseMainPage.vue
> +<v-container style="margin-top: 10%; background-color: rgb(var(--v-theme-surface));">
You're using a container here instead of a v-card. By using a v-card, you can also omit the background-color styling here, since cards are by default surface-colored.

2022-05-16 17:53 UTC, danielp0505 commented on src/components/CourseMainPage.vue
> +  <v-container style="background-color:rgb(var(--v-theme-primary));">
Changed the background color to a different green which is AA compliant

2022-05-17 11:59 UTC, hwgn approved these changes

2022-05-17 13:40 UTC, merged