34 admin panel navigation
THM-ATLAS/vue-frontend pull request #94
Opened 2022-05-14 17:08 UTC by shinymew2

Unter dem Pfad /admin/users kann man die Navbar testen

2022-05-14 18:54 UTC, hwgn requested changes
Looks really nice overall!

2022-05-14 18:54 UTC, hwgn commented on src/components/admin/NavbarAdmin.vue
> +    </v-list>
Could you add a "Leave" button to the bottom of the drawer? That way you don't get stuck in the admin area

2022-05-14 18:54 UTC, hwgn commented on src/components/admin/NavbarAdmin.vue
> +  <v-navigation-drawer permanent>
Is there some way to make it hide on smaller devices and only open on request?

2022-05-15 11:30 UTC, hwgn requested changes

2022-05-15 11:30 UTC, hwgn commented on src/views/admin/TaskManagementView.vue
>    <NavbarAdmin/>
The navbar is currently covering the content a little

2022-05-15 12:21 UTC, shinymew2 reviewed
Looks good.

2022-05-15 12:26 UTC, hwgn approved these changes
LGTM

2022-05-15 12:27 UTC, merged